# Generated by Django 4.1.7 on 2023-03-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('data', models.TextField()),
                ('tag', models.CharField(max_length=200)),
                ('main', models.CharField(max_length=200)),
            ],
        ),
    ]
